// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud or add them to your Vercel project settings.`;
    console.warn(`[Supabase] ${message}`);
    // Return a mock client that logs warnings instead of crashing the app
    return createMockClient(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

function createMockClient(missingMessage: string) {
  const warn = () => console.warn(`[Supabase] ${missingMessage}`);
  return new Proxy({} as ReturnType<typeof createClient<Database>>, {
    get(_, prop) {
      warn();
      // Return a mock object that also warns on any method call
      if (prop === 'auth') {
        return {
          getSession: async () => ({ data: { session: null }, error: null }),
          getUser: async () => ({ data: { user: null }, error: new Error(missingMessage) }),
          signInWithPassword: async () => ({ data: null, error: new Error(missingMessage) }),
          signUp: async () => ({ data: null, error: new Error(missingMessage) }),
          signOut: async () => {},
          onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
        };
      }
      if (prop === 'from') {
        return () => ({
          select: () => ({
            eq: () => ({
              order: () => ({
                then: async (resolve: Function) => resolve({ data: [], error: null }),
                data: [],
                error: null,
              }),
              data: [],
              error: null,
            }),
            order: () => ({
              then: async (resolve: Function) => resolve({ data: [], error: null }),
              data: [],
              error: null,
            }),
            then: async (resolve: Function) => resolve({ data: [], error: null }),
            data: [],
            error: null,
          }),
          insert: () => ({
            select: () => ({
              then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
              single: () => ({
                then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
              }),
            }),
            then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
          }),
          update: () => ({
            eq: () => ({
              select: () => ({
                then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
                single: () => ({
                  then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
                }),
              }),
              then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
            }),
            then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
          }),
          delete: () => ({
            eq: () => ({
              then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
            }),
            then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
          }),
          storage: {
            from: () => ({
              upload: async () => ({ data: null, error: new Error(missingMessage) }),
              getPublicUrl: () => ({ data: { publicUrl: '' } }),
              list: async () => ({ data: [], error: null }),
              remove: async () => ({ data: null, error: new Error(missingMessage) }),
            }),
          },
          rpc: () => ({
            then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
          }),
        });
      }
      if (prop === 'storage') {
        return {
          from: () => ({
            upload: async () => ({ data: null, error: new Error(missingMessage) }),
            getPublicUrl: () => ({ data: { publicUrl: '' } }),
            list: async () => ({ data: [], error: null }),
            remove: async () => ({ data: null, error: new Error(missingMessage) }),
          }),
        };
      }
      if (prop === 'rpc') {
        return () => ({
          then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
        });
      }
      if (prop === 'then') return undefined;
      return () => ({
        then: async (resolve: Function) => resolve({ data: null, error: new Error(missingMessage) }),
      });
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});